// Generated by ai-wingman — edit freely, you own this file.

import { convertToModelMessages, stepCountIs, streamText } from 'ai'
import { openai } from '@ai-sdk/openai'
import { myToolTools } from '@/lib/tools/my-tool.tools'

// Allow streaming responses up to 30 seconds
export const maxDuration = 30

export async function POST(req: Request) {
  // TODO: bring your own auth
  // Add session validation here before processing messages. Example with NextAuth:
  //   import { auth } from '@/auth'
  //   const session = await auth()
  //   if (!session) return new Response('Unauthorized', { status: 401 })

  const { messages } = await req.json()

  try {
    const result = streamText({
      model: openai("gpt-5.4-nano"),
      tools: myToolTools,
      stopWhen: stepCountIs(5),
      messages: await convertToModelMessages(messages),
      // onStepFinish: async ({ stepType, toolCalls, toolResults }) => {
      //   console.log({ stepType, toolCalls, toolResults })
      // },
    })
    return result.toUIMessageStreamResponse()
  } catch {
    return Response.json({ error: 'Internal server error' }, { status: 500 })
  }
}
