// Generated by ai-wingman — edit freely, you own this file.
//
// This is an autonomous agent with persistent memory.
// Each conversation is stored and resumed via conversationId.
// The agent calls tools in a loop (up to maxSteps times) before responding.

import { convertToModelMessages, generateId, stepCountIs, streamText } from 'ai'
import type { UIMessage } from 'ai'
import { __PROVIDER_IMPORT__ } from '__PROVIDER_PACKAGE__'
import { __TOOLS_VAR_NAME__ } from '__TOOLS_IMPORT_PATH__'
import { storage } from '__STORAGE_IMPORT_PATH__'
// __INJECT:AUTH_IMPORT__

// Allow streaming responses up to __MAX_DURATION__ seconds — agents may run multiple tool steps
export const maxDuration = __MAX_DURATION__

export async function POST(req: Request) {
// __INJECT:AUTH_CHECK__

  const { messages, conversationId } = await req.json()

  try {
    const result = streamText({
      model: __MODEL_FACTORY__,
      system: 'You are an autonomous agent. Use the available tools to complete tasks. Think step-by-step, calling tools as needed until the task is done.',
      tools: __TOOLS_VAR_NAME__,
      stopWhen: stepCountIs(__MAX_STEPS__),
      messages: await convertToModelMessages(messages),
      onFinish: async ({ response }) => {
        const assistantMessages: UIMessage[] = response.messages.map((m) => {
          const content = Array.isArray(m.content) ? m.content : [{ type: 'text', text: m.content }]
          return {
            id: generateId(),
            role: m.role as UIMessage['role'],
            parts: (content as Array<{ type: string; text?: string; [k: string]: unknown }>).flatMap((c) => {
              if (c.type === 'text') return [{ type: 'text' as const, text: c.text as string }]
              return []
            }),
            metadata: {},
          }
        })
        await storage.saveMessages(conversationId, [...messages, ...assistantMessages])
      },
    })
    return result.toUIMessageStreamResponse()
  } catch {
    return Response.json({ error: 'Internal server error' }, { status: 500 })
  }
}
