'use client'

// Generated by ai-wingman — edit freely, you own this file.
// TODO: Add layout and styling around this component

import { useCallback, useState } from 'react'
import { useChat } from '@ai-sdk/react'
import { DefaultChatTransport, isToolUIPart } from 'ai'
import {
  Conversation,
  ConversationContent,
  ConversationEmptyState,
  ConversationScrollButton,
} from '__PATH_ALIAS__components/ai-elements/conversation'
import {
  Message,
  MessageContent,
} from '__PATH_ALIAS__components/ai-elements/message'
import {
  PromptInput,
  PromptInputBody,
  PromptInputFooter,
  PromptInputSubmit,
  PromptInputTextarea,
  type PromptInputMessage,
} from '__PATH_ALIAS__components/ai-elements/prompt-input'

const API_PATH = '__API_PATH__'

export default function AgentPage() {
  // Each page mount gets a fresh conversation ID — the agent resumes it on reload.
  const [conversationId] = useState(() => crypto.randomUUID())

  const { messages, sendMessage, status } = useChat({
    transport: new DefaultChatTransport({
      api: API_PATH,
      body: { conversationId },
    }),
  })

  const handleSubmit = useCallback((msg: PromptInputMessage) => {
    if (msg.text?.trim()) sendMessage({ text: msg.text })
  }, [sendMessage])

  return (
    <div className="flex flex-col h-screen">
      <Conversation>
        <ConversationContent>
          {messages.length === 0 && (
            <ConversationEmptyState
              title="Agent ready"
              description="Describe a task and the agent will use its tools to complete it."
            />
          )}
          {messages.map((msg) => {
            if (msg.role === 'user') {
              const text = msg.parts
                .filter((p) => p.type === 'text')
                .map((p) => (p as { text: string }).text)
                .join('')
              return (
                <Message key={msg.id} from="user">
                  <MessageContent>{text}</MessageContent>
                </Message>
              )
            }

            if (msg.role === 'assistant') {
              const textParts = msg.parts.filter((p) => p.type === 'text')
              const toolParts = msg.parts.filter(isToolUIPart)
              if (textParts.length === 0 && toolParts.length === 0) return null

              return (
                <Message key={msg.id} from="assistant">
                  {textParts.map((p, i) => (
                    <MessageContent key={i}>
                      {(p as { text: string }).text}
                    </MessageContent>
                  ))}
                  {toolParts.map((p) => (
                    <MessageContent key={p.toolCallId}>
                      <span className="font-mono text-xs text-muted-foreground">
                        {String(p.type).replace('tool-', '')}
                        {p.state === 'input-available'
                          ? `(${JSON.stringify(p.input)})` : ''}
                        {p.state === 'output-available'
                          ? ` → ${JSON.stringify(p.output)}` : ''}
                      </span>
                    </MessageContent>
                  ))}
                </Message>
              )
            }

            return null
          })}
        </ConversationContent>
        <ConversationScrollButton />
      </Conversation>

      <PromptInput onSubmit={handleSubmit} className="border-t">
        <PromptInputBody>
          <PromptInputTextarea placeholder="Describe a task for the agent..." />
        </PromptInputBody>
        <PromptInputFooter>
          <PromptInputSubmit status={status} disabled={status !== 'ready'} />
        </PromptInputFooter>
      </PromptInput>
    </div>
  )
}
