// Generated by ai-wingman — edit freely, you own this file.

import { convertToModelMessages, generateId, streamText } from 'ai'
import type { UIMessage } from 'ai'
import { __PROVIDER_IMPORT__ } from '__PROVIDER_PACKAGE__'
import { storage } from '__STORAGE_IMPORT_PATH__'
// __INJECT:AUTH_IMPORT__

// Allow streaming responses up to __MAX_DURATION__ seconds
export const maxDuration = __MAX_DURATION__;

export async function POST(req: Request) {
// __INJECT:AUTH_CHECK__

  const { messages, conversationId } = await req.json()

  const result = streamText({
    model: __MODEL_FACTORY__,
    system: 'You are a helpful assistant.',
    messages: await convertToModelMessages(messages),
    onFinish: async ({ response }) => {
      // Convert ResponseMessage[] → UIMessage[] so stored messages can be
      // passed back to useChat as initialMessages on conversation load.
      const assistantMessages: UIMessage[] = response.messages.map((m) => {
        const content = Array.isArray(m.content) ? m.content : [{ type: 'text', text: m.content }]
        return {
          id: generateId(),
          role: m.role as UIMessage['role'],
          parts: (content as Array<{ type: string; text?: string; [k: string]: unknown }>).flatMap((c) => {
            if (c.type === 'text') return [{ type: 'text' as const, text: c.text as string }]
            return []
          }),
          metadata: {},
        }
      })
      await storage.saveMessages(conversationId, [...messages, ...assistantMessages])
    },
  })

  return result.toUIMessageStreamResponse({ sendReasoning: true, sendSources: true })
}
