// Generated by ai-wingman — edit freely, you own this file.

import { convertToModelMessages, streamText } from 'ai'
import { __PROVIDER_IMPORT__ } from '__PROVIDER_PACKAGE__'
// __INJECT:AUTH_IMPORT__

// Allow streaming responses up to __MAX_DURATION__ seconds
export const maxDuration = __MAX_DURATION__;

export async function POST(req: Request) {
// __INJECT:AUTH_CHECK__

  const { messages } = await req.json()

// __INJECT:STORAGE_STUB__

  const result = streamText({
    model: __MODEL_FACTORY__,
    system: 'You are a helpful assistant.',
    messages: await convertToModelMessages(messages),
  })

  return result.toUIMessageStreamResponse({ sendReasoning: true, sendSources: true })
}
