// Generated by ai-wingman — edit freely, you own this file.
//
// DATA FLOW — native approval (AI SDK v6)
// ─────────────────────────────────────────────────────────────────────────────
// 1. Model calls a tool with needsApproval: true
// 2. SDK pauses; streams state: 'approval-requested' to client
// 3. ApprovalWidget detects the pending approval and renders Approve / Reject
// 4. User clicks → addToolApprovalResponse({ id, approved })
// 5. SDK resumes; tool.execute() runs if approved
// ─────────────────────────────────────────────────────────────────────────────

import { convertToModelMessages, streamText } from 'ai'
import { __PROVIDER_IMPORT__ } from '__PROVIDER_PACKAGE__'
import { APPROVAL_TOOLS } from '__INTERRUPT_TOOLS_IMPORT_PATH__'
// __INJECT:AUTH_IMPORT__

// Allow streaming responses up to __MAX_DURATION__ seconds
export const maxDuration = __MAX_DURATION__;

export async function POST(req: Request) {
// __INJECT:AUTH_CHECK__

  const { messages } = await req.json()

// __INJECT:STORAGE_STUB__

  const result = streamText({
    model: __MODEL_FACTORY__,
    system: 'You are a helpful assistant.',
    messages: await convertToModelMessages(messages),
    tools: { ...APPROVAL_TOOLS },
  })

  return result.toUIMessageStreamResponse({ sendReasoning: true, sendSources: true })
}
