// Generated by ai-wingman — edit freely, you own this file.
//
// Speech-to-text: accepts a base64-encoded audio file and returns the transcript.
// Provider must support transcription (e.g. OpenAI Whisper via @ai-sdk/openai).
//
// Client sends: { audio: "<base64>", mimeType: "audio/webm" }
// Response:     { text: "transcribed content..." }

import { experimental_transcribe as transcribe } from 'ai'
import { __PROVIDER_IMPORT__ } from '__PROVIDER_PACKAGE__'
// __INJECT:AUTH_IMPORT__

export const maxDuration = __MAX_DURATION__

export async function POST(req: Request) {
// __INJECT:AUTH_CHECK__

  const { audio, mimeType = 'audio/webm' } = await req.json() as { audio: string; mimeType?: string }

  try {
    // Decode the base64 audio sent by the client
    const audioBuffer = Buffer.from(audio, 'base64')

    const result = await transcribe({
      // TODO: swap for your provider's transcription model, e.g. openai.transcription('whisper-1')
      model: __TRANSCRIPTION_CALL_EXPR__,
      audio: audioBuffer,
    })

    return Response.json({ text: result.text })
  } catch {
    return Response.json({ error: 'Transcription failed' }, { status: 500 })
  }
}
