'use client'

// Generated by ai-wingman — edit freely, you own this file.
// Transcribe: record audio → send base64 to /api/audio/transcribe → display text
// Speech:     type text → send to /api/audio/speech → play the returned audio

import { useRef, useState } from 'react'
import { Button } from '__PATH_ALIAS__components/ui/button'
import { Input } from '__PATH_ALIAS__components/ui/input'

const TRANSCRIBE_PATH = '__TRANSCRIBE_PATH__'
const SPEECH_PATH = '__SPEECH_PATH__'

export default function AudioPage() {
  const [transcript, setTranscript] = useState('')
  const [recording, setRecording] = useState(false)
  const mediaRef = useRef<MediaRecorder | null>(null)
  const chunksRef = useRef<BlobPart[]>([])
  const [ttsText, setTtsText] = useState('')
  const [playing, setPlaying] = useState(false)

  async function startRecording() {
    const stream = await navigator.mediaDevices.getUserMedia({ audio: true })
    const recorder = new MediaRecorder(stream)
    chunksRef.current = []
    recorder.ondataavailable = (e) => chunksRef.current.push(e.data)
    recorder.onstop = async () => {
      const blob = new Blob(chunksRef.current, { type: 'audio/webm' })
      const base64 = await blobToBase64(blob)
      const res = await fetch(TRANSCRIBE_PATH, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ audio: base64, mimeType: 'audio/webm' }),
      })
      const data = await res.json() as { text: string }
      setTranscript(data.text)
      stream.getTracks().forEach((t) => t.stop())
    }
    recorder.start()
    mediaRef.current = recorder
    setRecording(true)
  }

  function stopRecording() {
    mediaRef.current?.stop()
    setRecording(false)
  }

  function blobToBase64(blob: Blob): Promise<string> {
    return new Promise((resolve, reject) => {
      const reader = new FileReader()
      reader.onload = () => {
        const dataUrl = reader.result as string
        // strip the data:...;base64, prefix
        resolve(dataUrl.split(',')[1] ?? '')
      }
      reader.onerror = reject
      reader.readAsDataURL(blob)
    })
  }

  async function speak() {
    if (!ttsText.trim()) return
    setPlaying(true)
    try {
      const res = await fetch(SPEECH_PATH, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text: ttsText }),
      })
      const arrayBuffer = await res.arrayBuffer()
      const audioCtx = new AudioContext()
      const audioBuffer = await audioCtx.decodeAudioData(arrayBuffer)
      const source = audioCtx.createBufferSource()
      source.buffer = audioBuffer
      source.connect(audioCtx.destination)
      source.onended = () => setPlaying(false)
      source.start()
    } catch {
      setPlaying(false)
    }
  }

  return (
    <div className="max-w-lg mx-auto p-8 flex flex-col gap-8">
      <h1 className="text-2xl font-semibold">Audio</h1>

      {/* Transcription */}
      <section className="flex flex-col gap-3">
        <h2 className="text-lg font-medium">Speech → Text</h2>
        <Button
          onClick={recording ? stopRecording : startRecording}
          variant={recording ? 'destructive' : 'default'}
        >
          {recording ? 'Stop recording' : 'Start recording'}
        </Button>
        {transcript && (
          <p className="rounded border p-3 text-sm whitespace-pre-wrap">{transcript}</p>
        )}
      </section>

      {/* Text-to-speech */}
      <section className="flex flex-col gap-3">
        <h2 className="text-lg font-medium">Text → Speech</h2>
        <div className="flex gap-2">
          <Input
            value={ttsText}
            onChange={(e) => setTtsText(e.target.value)}
            placeholder="Enter text to speak..."
            onKeyDown={(e) => { if (e.key === 'Enter') void speak() }}
          />
          <Button onClick={() => void speak()} disabled={playing || !ttsText.trim()}>
            {playing ? 'Playing…' : 'Speak'}
          </Button>
        </div>
      </section>
    </div>
  )
}
