// Generated by ai-wingman — edit freely, you own this file.
//
// Text-to-speech: accepts text and streams back an audio file.
// Provider must support speech generation (e.g. OpenAI TTS via @ai-sdk/openai).
//
// Client sends: { text: "Hello world" }
// Response:     audio/mpeg stream

import { experimental_generateSpeech as generateSpeech } from 'ai'
import { __PROVIDER_IMPORT__ } from '__PROVIDER_PACKAGE__'
// __INJECT:AUTH_IMPORT__

export const maxDuration = __MAX_DURATION__

export async function POST(req: Request) {
// __INJECT:AUTH_CHECK__

  const { text } = await req.json() as { text: string }

  try {
    const result = await generateSpeech({
      // TODO: swap for your provider's speech model, e.g. openai.speech('tts-1')
      model: __SPEECH_CALL_EXPR__,
      text,
      voice: 'alloy', // TODO: choose a voice
    })

    return new Response(result.audio.uint8Array as unknown as BodyInit, { headers: { 'Content-Type': 'audio/mpeg' } })
  } catch {
    return Response.json({ error: 'Speech generation failed' }, { status: 500 })
  }
}
