'use client'

// Generated by ai-wingman — edit freely, you own this file.
// Transcribe: record audio → send base64 to /api/audio/transcribe → display text
// Speech:     type text → send to /api/audio/speech → play the returned audio

import { useRef, useState } from 'react'
import { Button } from '__PATH_ALIAS__components/ui/button'
import { Input } from '__PATH_ALIAS__components/ui/input'

const SPEECH_PATH = '__SPEECH_PATH__'

export default function AudioPage() {
  const [ttsText, setTtsText] = useState('')
  const [playing, setPlaying] = useState(false)

  async function speak() {
    if (!ttsText.trim()) return
    setPlaying(true)
    try {
      const res = await fetch(SPEECH_PATH, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text: ttsText }),
      })
      const arrayBuffer = await res.arrayBuffer()
      const audioCtx = new AudioContext()
      const audioBuffer = await audioCtx.decodeAudioData(arrayBuffer)
      const source = audioCtx.createBufferSource()
      source.buffer = audioBuffer
      source.connect(audioCtx.destination)
      source.onended = () => setPlaying(false)
      source.start()
    } catch {
      setPlaying(false)
    }
  }

  return (
    <div className="max-w-lg mx-auto p-8 flex flex-col gap-8">
      <h1 className="text-2xl font-semibold">Audio</h1>

      {/* Text-to-speech */}
      <section className="flex flex-col gap-3">
        <h2 className="text-lg font-medium">Text → Speech</h2>
        <div className="flex gap-2">
          <Input
            value={ttsText}
            onChange={(e) => setTtsText(e.target.value)}
            placeholder="Enter text to speak..."
            onKeyDown={(e) => { if (e.key === 'Enter') void speak() }}
          />
          <Button onClick={() => void speak()} disabled={playing || !ttsText.trim()}>
            {playing ? 'Playing…' : 'Speak'}
          </Button>
        </div>
      </section>
    </div>
  )
}
