// Generated by ai-wingman — edit freely, you own this file.
//
// Status/result polling route: returns { status, result?, error? } for a job.
// Poll at a sensible interval (e.g. every 2–5 s) until status === "done" | "failed".

import { jobStore } from '__JOB_STORE_IMPORT_PATH__'
// __INJECT:AUTH_IMPORT__

export async function GET(
  _req: Request,
  { params }: { params: Promise<{ jobId: string }> }
) {
// __INJECT:AUTH_CHECK__

  const { jobId } = await params
  const job = jobStore.get(jobId)
  if (!job) return Response.json({ error: 'Job not found' }, { status: 404 })

  return Response.json({
    status: job.status,
    ...(job.result !== undefined && { result: job.result }),
    ...(job.error !== undefined && { error: job.error }),
  })
}
