// Generated by ai-wingman — edit freely, you own this file.
//
// Enqueue route: creates a job, fires the worker asynchronously, and returns
// the jobId immediately — no waiting for the AI response.
//
// NOTE: void runWorker(...) works in Node.js servers (Railway, Fly, EC2) where
// the process stays alive. On serverless platforms (Vercel, Netlify) the
// function freezes after the response — use a real queue adapter instead.

import { generateId } from 'ai'
import { jobStore } from '__JOB_STORE_IMPORT_PATH__'
import { runWorker } from '__WORKER_IMPORT_PATH__'
// __INJECT:AUTH_IMPORT__

export async function POST(req: Request) {
// __INJECT:AUTH_CHECK__

  const { task } = await req.json()
  if (!task?.trim()) return Response.json({ error: 'task is required' }, { status: 400 })

  const jobId = generateId()
  jobStore.create(jobId, task)

  // Fire-and-forget: worker runs outside the request lifecycle
  void runWorker(jobId, task)

  return Response.json({ jobId }, { status: 202 })
}
