// Generated by ai-wingman — edit freely, you own this file.
//
// In-memory job store. Swap for a Redis adapter (Upstash, ioredis) or a
// queue-backed implementation (Inngest, BullMQ) for production.

export type JobStatus = 'pending' | 'running' | 'done' | 'failed'

export interface JobEntry {
  id: string
  task: string
  status: JobStatus
  result?: string
  error?: string
  createdAt: Date
  finishedAt?: Date
}

export interface JobStore {
  create(id: string, task: string): void
  setRunning(id: string): void
  setDone(id: string, result: string): void
  setFailed(id: string, error: string): void
  get(id: string): JobEntry | undefined
}

class InMemoryJobStore implements JobStore {
  private jobs = new Map<string, JobEntry>()

  create(id: string, task: string): void {
    this.jobs.set(id, { id, task, status: 'pending', createdAt: new Date() })
  }

  setRunning(id: string): void {
    const job = this.jobs.get(id)
    if (job) job.status = 'running'
  }

  setDone(id: string, result: string): void {
    const job = this.jobs.get(id)
    if (job) { job.status = 'done'; job.result = result; job.finishedAt = new Date() }
  }

  setFailed(id: string, error: string): void {
    const job = this.jobs.get(id)
    if (job) { job.status = 'failed'; job.error = error; job.finishedAt = new Date() }
  }

  get(id: string): JobEntry | undefined {
    return this.jobs.get(id)
  }
}

// Singleton — shared across hot-reloads in development
const globalForJobs = globalThis as typeof globalThis & { __jobStore?: InMemoryJobStore }
export const jobStore: JobStore = globalForJobs.__jobStore ??= new InMemoryJobStore()
