// Generated by ai-wingman — edit freely, you own this file.
//
// Worker function: processes a task outside the HTTP request cycle.
// Called with void (fire-and-forget) from the enqueue route.
// In production, replace this with an Inngest / BullMQ handler that
// receives the job payload from a real queue.

import { generateText, stepCountIs } from 'ai'
import { __PROVIDER_IMPORT__ } from '__PROVIDER_PACKAGE__'
import { jobStore } from '__JOB_STORE_IMPORT_PATH__'

export async function runWorker(jobId: string, task: string): Promise<void> {
  jobStore.setRunning(jobId)
  try {
    const { text } = await generateText({
      model: __MODEL_FACTORY__,
      system: 'You are an autonomous background agent. Complete the given task thoroughly and return a complete, self-contained result.',
      prompt: task,
      stopWhen: stepCountIs(20),
    })
    jobStore.setDone(jobId, text)
  } catch (err) {
    jobStore.setFailed(jobId, err instanceof Error ? err.message : 'Unknown error')
  }
}
