// Generated by ai-wingman — edit freely, you own this file.
// Add, remove, or edit categories to match your content policy.
// Each category is injected into the model's system prompt at runtime.

export interface PolicyCategory {
  name: string
  description: string
}

export const POLICY_CATEGORIES: PolicyCategory[] = [
  {
    name: 'hate-speech',
    description: 'Content that attacks or demeans groups based on protected characteristics',
  },
  {
    name: 'violence',
    description: 'Graphic descriptions or incitement of physical harm',
  },
  {
    name: 'spam',
    description: 'Unsolicited promotional content, repetitive noise, or automated gibberish',
  },
  {
    name: 'adult-content',
    description: 'Explicit sexual material not appropriate for general audiences',
  },
  {
    name: 'personal-information',
    description: 'Requests to share or expose sensitive personal data (passwords, SSNs, etc.)',
  },
]
