// Generated by ai-wingman — edit freely, you own this file.
//
// Content moderation route: classifies input against your policy categories.
// Edit lib/moderation/policy.ts to add, remove, or rename categories.
//
// See: https://ai-sdk.dev/docs/reference/ai-sdk-core/generate-text

import { generateText, Output } from 'ai'
import { __PROVIDER_IMPORT__ } from '__PROVIDER_PACKAGE__'
import { z } from 'zod'
import { POLICY_CATEGORIES } from '__POLICY_IMPORT_PATH__'
// __INJECT:AUTH_IMPORT__

export const maxDuration = __MAX_DURATION__

const moderationSchema = z.object({
  allowed: z.boolean().describe('Whether the content passes the policy'),
  category: z.string().describe('The violated policy category, or "none" if content is allowed'),
  reason: z.string().describe('Brief explanation of the decision'),
})

export async function POST(req: Request) {
// __INJECT:AUTH_CHECK__

  const { input } = await req.json()
  if (!input?.trim()) return Response.json({ error: 'input is required' }, { status: 400 })

  const categoryList = POLICY_CATEGORIES
    .map((c) => `- ${c.name}: ${c.description}`)
    .join('\n')

  const { output } = await generateText({
    model: __MODEL_FACTORY__,
    output: Output.object({ schema: moderationSchema }),
    system:
      'You are a content moderation classifier. Evaluate whether the content violates any policy.\n\n' +
      `Policy categories:\n${categoryList}\n\n` +
      'Return allowed: true if safe. If it violates a policy, set allowed: false, ' +
      'category to the violated category name, and reason to a brief explanation.',
    prompt: input,
  })

  return Response.json(output)
}
