// Generated by ai-wingman — edit freely, you own this file.

import { storage } from '__STORAGE_IMPORT_PATH__'
// __INJECT:AUTH_IMPORT__

export async function GET(
  _req: Request,
  { params }: { params: Promise<{ id: string }> }
) {
// __INJECT:AUTH_CHECK__
  const { id } = await params
  const messages = await storage.getMessages(id)
  if (!messages.length) return Response.json({ error: 'not found' }, { status: 404 })
  return Response.json({ messages })
}
