// Generated by ai-wingman — edit freely, you own this file.

import { storage } from '__STORAGE_IMPORT_PATH__'
// __INJECT:AUTH_IMPORT__

export async function POST() {
// __INJECT:AUTH_CHECK__
  const id = await storage.createConversation()
  return Response.json({ id, createdAt: new Date().toISOString() }, { status: 201 })
}

export async function GET() {
// __INJECT:AUTH_CHECK__
  const conversations = await storage.listConversations()
  return Response.json({ conversations })
}
