// Generated by ai-wingman — edit freely, you own this file.
//
// Accepts a multipart/form-data upload with a "file" field (PDF or text),
// passes it to the model as a file message part, and returns typed JSON.
//
// Provider support: Anthropic (recommended), Google Gemini.
// OpenAI does not support inline PDF file parts — use text extraction first.
// See: https://sdk.vercel.ai/docs/ai-sdk-core/files

import { generateText, Output } from 'ai'
import { __PROVIDER_IMPORT__ } from '__PROVIDER_PACKAGE__'
import { __SCHEMA_VAR_NAME__ } from '__SCHEMA_IMPORT_PATH__'
// __INJECT:AUTH_IMPORT__

export const maxDuration = __MAX_DURATION__

export async function POST(req: Request) {
// __INJECT:AUTH_CHECK__

  const form = await req.formData()
  const file = form.get('file') as File | null

  if (!file) {
    return Response.json({ error: 'No file provided' }, { status: 400 })
  }

  const bytes = await file.arrayBuffer()
  const base64 = Buffer.from(bytes).toString('base64')
  const mimeType = file.type || 'application/pdf'

  const { output } = await generateText({
    model: __MODEL_FACTORY__,
    output: Output.object({ schema: __SCHEMA_VAR_NAME__ }),
    messages: [
      {
        role: 'user',
        content: [
          { type: 'file', data: base64, mimeType },
          {
            type: 'text',
            text: 'Extract the structured data from this document. Return only the fields defined in the schema.',
          },
        ],
      },
    ],
  })

  return Response.json(output)
}
