// Generated by ai-wingman — edit freely, you own this file.

import { useState } from 'react'
import type { __TYPE_NAME__ } from '__SCHEMA_IMPORT_PATH__'

export function __HOOK_NAME__() {
  const [result, setResult] = useState<__TYPE_NAME__ | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  async function extract(file: File) {
    setLoading(true)
    setError(null)
    setResult(null)
    try {
      const form = new FormData()
      form.append('file', file)
      const res = await fetch('__API_URL__', { method: 'POST', body: form })
      if (!res.ok) throw new Error(`Request failed: ${res.status}`)
      setResult(await res.json() as __TYPE_NAME__)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Unknown error')
    } finally {
      setLoading(false)
    }
  }

  return { result, loading, error, extract }
}
