// Generated by ai-wingman — edit freely, you own this file.
// Customize these fields to match the documents you are processing.

import { z } from 'zod'

export const __SCHEMA_VAR_NAME__ = z.object({
  title:     z.string().optional().describe('Document title or main heading'),
  summary:   z.string().describe('Brief summary of the document content'),
  keyPoints: z.array(z.string()).describe('Key points or takeaways'),
  date:      z.string().optional().describe('Document date if present (ISO 8601)'),
  author:    z.string().optional().describe('Author or issuing entity'),
  // TODO: add fields specific to your document type, e.g.:
  // invoiceNumber: z.string().optional(),
  // lineItems: z.array(z.object({ description: z.string(), amount: z.number() })).optional(),
})

export type __TYPE_NAME__ = z.infer<typeof __SCHEMA_VAR_NAME__>
