// Generated by ai-wingman — edit freely, you own this file.
//
// API route for generative UI: model streams text and calls tools.
// Each tool maps to a React component rendered client-side in the page.
// Add more tools here, then handle them in page.tsx.
//
// See: https://ai-sdk.dev/docs/ai-sdk-ui/generative-user-interfaces

import { convertToModelMessages, streamText } from 'ai'
import { __PROVIDER_IMPORT__ } from '__PROVIDER_PACKAGE__'
import { z } from 'zod'
// __INJECT:AUTH_IMPORT__

// Allow streaming responses up to 30 seconds
export const maxDuration = 30

export async function POST(req: Request) {
// __INJECT:AUTH_CHECK__

  const { messages } = await req.json()

  try {
    const result = streamText({
      model: __MODEL_FACTORY__,
      system:
        'You are a helpful assistant. ' +
        'Use the card tool to display a titled piece of information. ' +
        'For plain answers, just respond with text.',
      tools: {
        // card — renders as a titled card component in the UI
        card: {
          description: 'Display a titled card with body text.',
          parameters: z.object({
            title: z.string().describe('Card heading'),
            body: z.string().describe('Card body text'),
          }),
        },
      },
      messages: await convertToModelMessages(messages),
    })
    return result.toUIMessageStreamResponse()
  } catch {
    return Response.json({ error: 'Internal server error' }, { status: 500 })
  }
}
