'use client'

// Generated by ai-wingman — edit freely, you own this file.
// Chat page that streams text and renders tool calls as React components.
// The model calls the card tool to display structured content.
// Add a new tool in route.ts and render it below in the parts loop.
//
// See: https://ai-sdk.dev/docs/ai-sdk-ui/generative-user-interfaces

import { useChat } from '@ai-sdk/react'
import { DefaultChatTransport } from 'ai'
import { Button } from '__PATH_ALIAS__components/ui/button'
import { Textarea } from '__PATH_ALIAS__components/ui/textarea'

export default function GenerativeUIPage() {
  const { messages, sendMessage, status } = useChat({
    transport: new DefaultChatTransport({ api: '__API_PATH__' }),
  })

  return (
    <div className="flex flex-col h-screen max-w-2xl mx-auto p-4 gap-4">
      <h1 className="text-xl font-semibold">Generative UI</h1>

      <div className="flex-1 overflow-y-auto flex flex-col gap-3">
        {messages.map((msg) => (
          <div
            key={msg.id}
            className={`text-sm ${
              msg.role === 'user' ? 'self-end max-w-xs rounded-lg bg-blue-50 p-3' : 'self-start w-full space-y-2'
            }`}
          >
            {msg.parts.map((part, i) => {
              if (part.type === 'text') {
                return <p key={i} className="leading-relaxed">{(part as any).text}</p>
              }
              if (part.type.startsWith('tool-')) {
                const p = part as any
                // Loading skeleton while tool input streams in
                if (p.state !== 'output-available') {
                  return (
                    <div key={i} className="rounded-lg border p-4 space-y-2 animate-pulse">
                      <div className="h-4 w-1/3 rounded bg-muted" />
                      <div className="h-3 w-2/3 rounded bg-muted" />
                    </div>
                  )
                }
                // card tool — renders a titled card
                if (p.toolName === 'card') {
                  return (
                    <div key={i} className="rounded-lg border p-4 space-y-1">
                      <h3 className="text-sm font-semibold">{p.input?.title}</h3>
                      <p className="text-sm text-muted-foreground">{p.input?.body}</p>
                    </div>
                  )
                }
                // Fallback for any other tools you add
                return (
                  <span key={i} className="font-mono text-xs text-muted-foreground">
                    {p.toolName} → {JSON.stringify(p.output)}
                  </span>
                )
              }
              return null
            })}
          </div>
        ))}
      </div>

      <form
        onSubmit={(e) => {
          e.preventDefault()
          const input = (e.currentTarget.elements.namedItem('message') as HTMLInputElement)
          if (input.value.trim()) {
            sendMessage({ text: input.value })
            input.value = ''
          }
        }}
        className="flex gap-2 items-end"
      >
        <Textarea
          name="message"
          placeholder="Ask something…"
          rows={2}
          disabled={status !== 'ready'}
          onKeyDown={(e) => {
            if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) {
              e.currentTarget.form?.requestSubmit()
            }
          }}
          className="resize-none flex-1"
        />
        <Button type="submit" disabled={status !== 'ready'}>
          Send
        </Button>
      </form>
    </div>
  )
}
