// Generated by ai-wingman — edit freely, you own this file.
//
// Extended RAG store that adds getAll() for BM25 keyword search.
// Implements the same upsert / query interface as the rag pattern's RagStore,
// so it is a drop-in upgrade — swap getRagStore() for getHybridStore() in your
// embed route and this store handles both vector and keyword search.

import { cosineSimilarity } from 'ai'

export interface HybridChunk {
  id: string
  text: string
  embedding?: number[]
}

export interface HybridStore {
  upsert(chunk: Required<HybridChunk>): Promise<void>
  query(params: { embedding: number[]; topK: number }): Promise<HybridChunk[]>
  /** Returns all stored chunks (text only — no embeddings) for BM25 scoring. */
  getAll(): Promise<HybridChunk[]>
}

export class MemoryHybridStore implements HybridStore {
  private chunks: Required<HybridChunk>[] = []

  async upsert(chunk: Required<HybridChunk>): Promise<void> {
    const idx = this.chunks.findIndex((c) => c.id === chunk.id)
    if (idx >= 0) {
      this.chunks[idx] = chunk
    } else {
      this.chunks.push(chunk)
    }
  }

  async query({ embedding, topK }: { embedding: number[]; topK: number }): Promise<HybridChunk[]> {
    return this.chunks
      .map((c) => ({ chunk: c, score: cosineSimilarity(embedding, c.embedding) }))
      .sort((a, b) => b.score - a.score)
      .slice(0, topK)
      .map(({ chunk }) => ({ id: chunk.id, text: chunk.text }))
  }

  async getAll(): Promise<HybridChunk[]> {
    return this.chunks.map((c) => ({ id: c.id, text: c.text }))
  }
}

let _store: HybridStore | undefined

export function getHybridStore(): HybridStore {
  if (!_store) _store = new MemoryHybridStore()
  return _store
}
