// Generated by ai-wingman — edit freely, you own this file.
//
// Hybrid search route: runs vector similarity and BM25 keyword search in parallel,
// then merges results with Reciprocal Rank Fusion before generating an answer.
//
// To index documents, call POST /api/rag/embed (or your embed route) using
// getHybridStore() instead of getRagStore() so getAll() is available for BM25.
//
// See: https://ai-sdk.dev/docs/ai-sdk-core/embeddings

import { embed, generateText } from 'ai'
import { __PROVIDER_IMPORT__ } from '__PROVIDER_PACKAGE__'
import { getHybridStore } from '__STORE_IMPORT_PATH__'
import { scoreBM25 } from '__BM25_IMPORT_PATH__'
import { reciprocalRankFusion } from '__RERANKER_IMPORT_PATH__'
// __INJECT:AUTH_IMPORT__

export const maxDuration = 30

export async function POST(req: Request) {
// __INJECT:AUTH_CHECK__

  const { query, topK = 5 } = await req.json()
  if (!query?.trim()) return Response.json({ error: 'query is required' }, { status: 400 })

  const store = getHybridStore()

  // Run embedding + fetch all docs in parallel
  const [{ embedding }, allDocs] = await Promise.all([
    embed({
      model: __EMBEDDING_CALL_EXPR__,
      value: query,
    }),
    store.getAll(),
  ])

  // Run vector and keyword search in parallel
  const [vectorResults, bm25Results] = await Promise.all([
    store.query({ embedding, topK: topK * 3 }),
    Promise.resolve(scoreBM25(allDocs, query, topK * 3)),
  ])

  // Merge with Reciprocal Rank Fusion
  const merged = reciprocalRankFusion(
    [
      vectorResults.map((c, i) => ({ id: c.id, rank: i })),
      bm25Results.map((r, i) => ({ id: r.id, rank: i })),
    ],
    topK,
  )

  const docMap = new Map(allDocs.map((d) => [d.id, d.text]))
  const context = merged.map((r) => docMap.get(r.id) ?? '').filter(Boolean).join('\n\n')

  const { text } = await generateText({
    model: __MODEL_FACTORY__,
    system: [
      'Answer using only the context below. If the answer is not in the context, say so.',
      '',
      'Context:',
      context,
    ].join('\n'),
    prompt: query,
  })

  return Response.json({ text, sources: merged })
}
