// Generated by ai-wingman — edit freely, you own this file.
//
// Reciprocal Rank Fusion (RRF) — merges multiple ranked lists into a single ranking.
// Each list contributes a score of 1 / (k + rank + 1) per document; scores are summed.
// RRF is robust across different scoring scales and requires no calibration.
//
// See: https://plg.uwaterloo.ca/~gvcormac/cormacksigir09-rrf.pdf

/** Constant from the original RRF paper. Higher values reduce the impact of top-ranked items. */
const RRF_K = 60

export interface RankedItem {
  id: string
  /** 0-indexed rank within its source list */
  rank: number
}

/**
 * Fuse multiple ranked lists into one using Reciprocal Rank Fusion.
 * Returns results sorted by descending score, limited to topK.
 */
export function reciprocalRankFusion(
  rankings: RankedItem[][],
  topK = Infinity,
): { id: string; score: number }[] {
  const scores = new Map<string, number>()

  for (const ranking of rankings) {
    for (const { id, rank } of ranking) {
      scores.set(id, (scores.get(id) ?? 0) + 1 / (RRF_K + rank + 1))
    }
  }

  const sorted = [...scores.entries()]
    .map(([id, score]) => ({ id, score }))
    .sort((a, b) => b.score - a.score)

  return topK === Infinity ? sorted : sorted.slice(0, topK)
}
