// Generated by ai-wingman — edit freely, you own this file.
//
// Pure BM25 scorer — no external dependencies.
// BM25 ranks documents by term frequency (TF) and inverse document frequency (IDF),
// normalised by document length. Adjust K1 and B to tune retrieval behaviour.
//
// See: https://en.wikipedia.org/wiki/Okapi_BM25

const K1 = 1.5  // Term frequency saturation (higher = more weight to rare terms)
const B = 0.75  // Document length normalisation (1.0 = full normalisation, 0 = none)

function tokenize(text: string): string[] {
  return text.toLowerCase().match(/\b\w+\b/g) ?? []
}

export interface BM25Document {
  id: string
  text: string
}

/**
 * Score all documents against a query and return the top-K results sorted by score.
 * Returns an empty array if there are no documents or query terms.
 */
export function scoreBM25(
  docs: BM25Document[],
  query: string,
  topK = docs.length,
): { id: string; score: number }[] {
  if (docs.length === 0) return []

  const queryTerms = tokenize(query)
  if (queryTerms.length === 0) return []

  const tokenizedDocs = docs.map((d) => tokenize(d.text))
  const avgLen = tokenizedDocs.reduce((s, t) => s + t.length, 0) / tokenizedDocs.length

  // Build document frequency map
  const df = new Map<string, number>()
  for (const terms of tokenizedDocs) {
    for (const term of new Set(terms)) {
      df.set(term, (df.get(term) ?? 0) + 1)
    }
  }

  const idf = (term: string): number => {
    const n = df.get(term) ?? 0
    return Math.log((docs.length - n + 0.5) / (n + 0.5) + 1)
  }

  const scores = docs.map((doc, i) => {
    const terms = tokenizedDocs[i]!
    const len = terms.length
    const tf = new Map<string, number>()
    for (const term of terms) tf.set(term, (tf.get(term) ?? 0) + 1)

    let score = 0
    for (const term of queryTerms) {
      const f = tf.get(term) ?? 0
      if (f === 0) continue
      score += idf(term) * (f * (K1 + 1)) / (f + K1 * (1 - B + B * (len / avgLen)))
    }
    return { id: doc.id, score }
  })

  return scores
    .filter((s) => s.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, topK)
}
