// Generated by ai-wingman — edit freely, you own this file.
//
// Accepts { prompt } and returns a generated image as a base64 data URL.
// Requires OPENAI_API_KEY — image generation uses OpenAI DALL·E models.
//
// See: https://sdk.vercel.ai/docs/ai-sdk-core/image-generation

import { generateImage } from 'ai'
import { openai } from '@ai-sdk/openai'
// __INJECT:AUTH_IMPORT__

export const maxDuration = __MAX_DURATION__

export async function POST(req: Request) {
// __INJECT:AUTH_CHECK__

  const { prompt } = await req.json() as { prompt: string }

  const { image } = await generateImage({
    model: openai.image('__IMAGE_MODEL__'),
    prompt,
  })

  return Response.json({ url: `data:${image.mediaType};base64,${image.base64}` })
}
