'use client'

// Generated by ai-wingman — edit freely, you own this file.
// Sends a text prompt to __API_PATH__ and displays the generated image.
// Includes a download button so the user can save the result.

import { useState } from 'react'
import { Button } from '__PATH_ALIAS__components/ui/button'
import { Textarea } from '__PATH_ALIAS__components/ui/textarea'

const API_PATH = '__API_PATH__'

export default function ImageGenPage() {
  const [prompt, setPrompt] = useState('')
  const [imageUrl, setImageUrl] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  async function generate() {
    if (!prompt.trim()) return
    setLoading(true)
    setError(null)
    setImageUrl(null)
    try {
      const res = await fetch(API_PATH, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt }),
      })
      if (!res.ok) throw new Error(`Request failed: ${res.status}`)
      const data = await res.json() as { url: string }
      setImageUrl(data.url)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Something went wrong')
    } finally {
      setLoading(false)
    }
  }

  function download() {
    if (!imageUrl) return
    const a = document.createElement('a')
    a.href = imageUrl
    a.download = 'generated-image.png'
    a.click()
  }

  return (
    <div className="max-w-xl mx-auto p-8 flex flex-col gap-6">
      <h1 className="text-2xl font-semibold">Image Generation</h1>

      <div className="flex flex-col gap-3">
        <Textarea
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          placeholder="Describe the image you want to generate…"
          rows={3}
          onKeyDown={(e) => {
            if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) void generate()
          }}
        />
        <Button onClick={() => void generate()} disabled={loading || !prompt.trim()}>
          {loading ? 'Generating…' : 'Generate'}
        </Button>
      </div>

      {error && (
        <p className="text-sm text-destructive">{error}</p>
      )}

      {imageUrl && (
        <div className="flex flex-col gap-3">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src={imageUrl} alt="Generated image" className="w-full rounded-md border" />
          <Button variant="outline" onClick={download}>
            Download image
          </Button>
        </div>
      )}
    </div>
  )
}
