// Generated by ai-wingman — edit freely, you own this file.
//
// Human-in-the-loop via needsApproval (AI SDK v6 native pattern)
// ─────────────────────────────────────────────────────────────────────────────
// 1. Client sends messages → POST /api/interrupt
// 2. streamText calls a tool with needsApproval: true
// 3. SDK streams state: "approval-requested" to the client
// 4. ApprovalWidget renders Approve / Reject buttons
// 5. useChat's addToolApprovalResponse(id, approved) re-submits the decision
// 6. SDK resumes: executes tool on approval, or skips on rejection
// ─────────────────────────────────────────────────────────────────────────────

import { convertToModelMessages, stepCountIs, streamText } from 'ai'
import { __PROVIDER_IMPORT__ } from '__PROVIDER_PACKAGE__'
import { APPROVAL_TOOLS } from '__TOOLS_IMPORT_PATH__'

// Allow streaming responses up to 30 seconds
export const maxDuration = 30

export async function POST(req: Request) {
  const { messages } = await req.json()

  const result = streamText({
    model: __MODEL_FACTORY__,
    system: 'You are a helpful assistant. Use the available tools to complete tasks.',
    tools: APPROVAL_TOOLS,
    stopWhen: stepCountIs(5),
    messages: await convertToModelMessages(messages),
  })

  return result.toUIMessageStreamResponse()
}
