// Generated by ai-wingman — edit freely, you own this file.
//
// Add needsApproval: true to any tool that requires human sign-off before executing.
// The SDK will pause execution and stream state: 'approval-requested' to the client.

import { tool } from 'ai'
import { z } from 'zod'

export const sendEmail = tool({
  description: 'Send an email to a recipient',
  inputSchema: z.object({
    to: z.string().email(),
    subject: z.string(),
    body: z.string(),
  }),
  // Pause and ask for human approval before executing
  needsApproval: true,
  execute: async ({ to, subject }: { to: string; subject: string; body: string }) => ({ sent: true, to, subject }),
})

// Add all tools that need approval here
export const APPROVAL_TOOLS = { sendEmail }
