// Generated by ai-wingman — edit freely, you own this file.

'use client'

import { useChat } from '@ai-sdk/react'
import { DefaultChatTransport } from 'ai'
import { ApprovalWidget } from '__WIDGET_IMPORT_PATH__'

export default function InterruptPage() {
  const { messages, sendMessage, status, addToolApprovalResponse } = useChat({
    transport: new DefaultChatTransport({ api: '__API_PATH__' }),
  })

  return (
    <div className="flex flex-col h-screen max-w-2xl mx-auto p-4 gap-4">
      <div className="flex-1 overflow-y-auto flex flex-col gap-3">
        {messages.map((msg) => (
          <div
            key={msg.id}
            className={`rounded-lg p-3 text-sm ${
              msg.role === 'user' ? 'bg-blue-50 self-end' : 'bg-gray-50 self-start'
            }`}
          >
            {msg.parts.map((part, i) => {
              if (part.type === 'text') {
                return <p key={i}>{(part as any).text}</p>
              }
              if (part.type.startsWith('tool-')) {
                const p = part as any
                return (
                  <span key={i} className="font-mono text-xs text-muted-foreground">
                    {p.toolName ?? String(part.type).replace('tool-', '')}
                    {p.state === 'output-available' ? ` → ${JSON.stringify(p.output)}` : ' …'}
                  </span>
                )
              }
              return null
            })}
          </div>
        ))}
      </div>

      {/* Approval widget renders above the input when a pending approval exists */}
      <ApprovalWidget messages={messages} addToolApprovalResponse={addToolApprovalResponse} />

      <form
        onSubmit={(e) => {
          e.preventDefault()
          const input = (e.currentTarget.elements.namedItem('message') as HTMLInputElement)
          if (input.value.trim()) {
            sendMessage({ text: input.value })
            input.value = ''
          }
        }}
        className="flex gap-2"
      >
        <input
          name="message"
          placeholder="Type a message..."
          disabled={status !== 'ready'}
          className="flex-1 border rounded px-3 py-2 text-sm"
        />
        <button
          type="submit"
          disabled={status !== 'ready'}
          className="px-4 py-2 bg-blue-600 text-white text-sm rounded hover:bg-blue-700 disabled:opacity-50"
        >
          Send
        </button>
      </form>
    </div>
  )
}
