'use client'
// Generated by ai-wingman — edit freely, you own this file.

import { isToolUIPart } from 'ai'
import type { UIMessage } from 'ai'

interface ApprovalWidgetProps {
  messages: UIMessage[]
  addToolApprovalResponse: (opts: { id: string; approved: boolean; reason?: string }) => void
}

export function ApprovalWidget({ messages, addToolApprovalResponse }: ApprovalWidgetProps) {
  const pending = messages
    .flatMap((m) => m.parts)
    .filter(isToolUIPart)
    .filter((p) => p.state === 'approval-requested')

  if (pending.length === 0) return null

  return (
    <div style={{ padding: '12px', border: '1px solid #e5e7eb', borderRadius: '8px', margin: '8px 0' }}>
      {pending.map((p) => (
        <div key={p.toolCallId}>
          <p style={{ margin: '0 0 8px', fontSize: '14px' }}>
            Approve <strong>{String(p.type).replace('tool-', '')}</strong>?
          </p>
          <div style={{ display: 'flex', gap: '8px' }}>
            <button
              onClick={() => addToolApprovalResponse({ id: p.approval.id, approved: true })}
              style={{ padding: '4px 12px', background: '#16a34a', color: '#fff', border: 'none', borderRadius: '4px', cursor: 'pointer' }}
            >
              Approve
            </button>
            <button
              onClick={() => addToolApprovalResponse({ id: p.approval.id, approved: false, reason: 'User rejected' })}
              style={{ padding: '4px 12px', background: '#dc2626', color: '#fff', border: 'none', borderRadius: '4px', cursor: 'pointer' }}
            >
              Reject
            </button>
          </div>
        </div>
      ))}
    </div>
  )
}
