// Generated by ai-wingman — edit freely, you own this file.

const store = new Map<string, unknown>()

export function getState<T>(key: string): T | undefined {
  return store.get(key) as T | undefined
}

export function setState<T>(key: string, value: T): void {
  store.set(key, value)
}
