// Generated by ai-wingman — edit freely, you own this file.

import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import { WebStandardStreamableHTTPServerTransport } from '@modelcontextprotocol/sdk/server/webStandardStreamableHttp.js'
import { randomUUID } from 'crypto'
import { readFileSync } from 'fs'
import { join } from 'path'
import { z } from 'zod'
// __INJECT:STATE_IMPORT__
// __INJECT:AUTH_IMPORT__

// fs and crypto require Node.js runtime
export const runtime = 'nodejs'

const RESOURCE_URI = '__RESOURCE_URI__'
// Standard MIME type for MCP App HTML resources — hosts use this to identify interactive UIs
const RESOURCE_MIME_TYPE = 'text/html;profile=mcp-app'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, mcp-session-id, mcp-protocol-version',
  'Access-Control-Expose-Headers': 'mcp-session-id',
}

function withCors(response: Response): Response {
  const newResponse = new Response(response.body, response)
  Object.entries(corsHeaders).forEach(([key, value]) => {
    newResponse.headers.set(key, value)
  })
  return newResponse
}

// Session store — persists across requests within the Node.js process lifetime
const sessions = new Map<string, WebStandardStreamableHTTPServerTransport>()

function createServer() {
  const server = new McpServer({ name: '__APP_NAME_PASCAL__', version: '1.0.0' })

  // Resource: the interactive HTML UI bundle.
  // mimeType must be 'text/html;profile=mcp-app' so hosts identify this as an MCP App.
  server.resource(RESOURCE_URI, RESOURCE_URI, { mimeType: RESOURCE_MIME_TYPE }, async () => ({
    contents: [{
      uri: RESOURCE_URI,
      mimeType: RESOURCE_MIME_TYPE,
      text: readFileSync(join(process.cwd(), '__UI_BUNDLE_PATH__'), 'utf-8'),
    }],
  }))

  // Tool: _meta.ui.resourceUri in the tool DEFINITION (not the result) tells hosts to render the UI.
  server.registerTool(
    '__TOOL_NAME__',
    {
      description: 'Describe what this tool does',
      inputSchema: { input: z.string().describe('The input for this tool') },
      _meta: {
        ui: { resourceUri: RESOURCE_URI },
        'ui/resourceUri': RESOURCE_URI, // legacy compat for older hosts
      },
    },
    async ({ input }) => {
// __INJECT:TOOL_BODY__
      return {
        content: [{ type: 'text' as const, text: `Result for: ${input}` }],
      }
    }
  )

  return server
}

// Helper — create a new transport+server pair, store session, return the response
async function handleNewSession(req: Request): Promise<Response> {
  const transport = new WebStandardStreamableHTTPServerTransport({
    sessionIdGenerator: () => randomUUID(),
  })
  const server = createServer()
  await server.connect(transport)
  const response = await transport.handleRequest(req)
  if (transport.sessionId) {
    sessions.set(transport.sessionId, transport)
    transport.onclose = () => sessions.delete(transport.sessionId!)
  }
  return response
}

// OPTIONS — handle CORS preflight
export async function OPTIONS() {
  return new Response(null, { status: 204, headers: corsHeaders })
}

// GET — SSE stream for existing session (server-to-client notifications)
export async function GET(req: Request) {
// __INJECT:AUTH_CHECK__
  const sessionId = req.headers.get('mcp-session-id')
  if (sessionId) {
    const transport = sessions.get(sessionId)
    if (!transport) return withCors(new Response('Session not found', { status: 404 }))
    return withCors(await transport.handleRequest(req))
  }
  return withCors(await handleNewSession(req))
}

// POST — initialize (no session ID) or route to existing session
export async function POST(req: Request) {
// __INJECT:AUTH_CHECK__
  const sessionId = req.headers.get('mcp-session-id')
  if (!sessionId) return withCors(await handleNewSession(req))
  const transport = sessions.get(sessionId)
  if (!transport) return withCors(new Response('Session not found', { status: 404 }))
  return withCors(await transport.handleRequest(req))
}

// DELETE — terminate session and release resources
export async function DELETE(req: Request) {
  const sessionId = req.headers.get('mcp-session-id')
  if (sessionId) {
    await sessions.get(sessionId)?.close()
    sessions.delete(sessionId)
  }
  return withCors(new Response(null, { status: 204 }))
}
