// Generated by ai-wingman — edit freely, you own this file.
//
// Retrieve route: embeds the query and returns the top-K most relevant memories.
// POST body: { userId: string, query: string, topK?: number }

import { embed } from 'ai'
import { __PROVIDER_IMPORT__ } from '__PROVIDER_PACKAGE__'
import { getMemoryStore } from '__STORE_IMPORT_PATH__'
// __INJECT:AUTH_IMPORT__

export async function POST(req: Request) {
// __INJECT:AUTH_CHECK__

  const { userId, query, topK = 5 } = await req.json()
  if (!userId?.trim() || !query?.trim())
    return Response.json({ error: 'userId and query are required' }, { status: 400 })

  const { embedding } = await embed({
    model: __EMBEDDING_CALL_EXPR__,
    value: query,
  })

  const memories = await getMemoryStore().retrieve(userId, { embedding, topK })

  return Response.json({ memories })
}
