// Generated by ai-wingman — edit freely, you own this file.
//
// buildMemoryContext — retrieves relevant memories for a user and formats them
// as a string you can prepend to your system prompt.
//
// Usage in a chat or agent route:
//
//   const memoryContext = await buildMemoryContext(userId, userMessage)
//   const result = streamText({
//     system: ['You are a helpful assistant.', memoryContext].filter(Boolean).join('\n\n'),
//     ...
//   })

import { embed } from 'ai'
import { __PROVIDER_IMPORT__ } from '__PROVIDER_PACKAGE__'
import { getMemoryStore } from '__STORE_IMPORT_PATH__'

export async function buildMemoryContext(
  userId: string,
  query: string,
  topK = 5,
): Promise<string> {
  const { embedding } = await embed({
    model: __EMBEDDING_CALL_EXPR__,
    value: query,
  })

  const memories = await getMemoryStore().retrieve(userId, { embedding, topK })
  if (memories.length === 0) return ''

  return [
    'Relevant memories about this user:',
    ...memories.map((m) => `- ${m.fact}`),
  ].join('\n')
}
