// Generated by ai-wingman — edit freely, you own this file.
//
// Per-user long-term memory store.
// The in-memory implementation is fine for development.
// Replace InMemoryMemoryStore with a database-backed adapter for production
// (e.g. PostgreSQL + pgvector, Redis, or any vector database).

import { cosineSimilarity } from 'ai'

export interface MemoryEntry {
  id: string
  userId: string
  fact: string
  embedding: number[]
  createdAt: Date
}

export interface MemoryStore {
  save(entry: MemoryEntry): Promise<void>
  retrieve(userId: string, params: { embedding: number[]; topK: number }): Promise<Pick<MemoryEntry, 'fact'>[]>
  clear(userId: string): Promise<void>
}

export class InMemoryMemoryStore implements MemoryStore {
  private entries: MemoryEntry[] = []

  async save(entry: MemoryEntry): Promise<void> {
    const idx = this.entries.findIndex((e) => e.id === entry.id)
    if (idx >= 0) {
      this.entries[idx] = entry
    } else {
      this.entries.push(entry)
    }
  }

  async retrieve(
    userId: string,
    { embedding, topK }: { embedding: number[]; topK: number },
  ): Promise<Pick<MemoryEntry, 'fact'>[]> {
    return this.entries
      .filter((e) => e.userId === userId)
      .map((e) => ({ entry: e, score: cosineSimilarity(embedding, e.embedding) }))
      .sort((a, b) => b.score - a.score)
      .slice(0, topK)
      .map(({ entry }) => ({ fact: entry.fact }))
  }

  async clear(userId: string): Promise<void> {
    this.entries = this.entries.filter((e) => e.userId !== userId)
  }
}

let _store: MemoryStore | undefined

export function getMemoryStore(): MemoryStore {
  if (!_store) _store = new InMemoryMemoryStore()
  return _store
}
