// Generated by ai-wingman — edit freely, you own this file.
//
// Save route: embeds a fact and stores it in the per-user memory store.
// POST body: { userId: string, fact: string }

import { embed, generateId } from 'ai'
import { __PROVIDER_IMPORT__ } from '__PROVIDER_PACKAGE__'
import { getMemoryStore } from '__STORE_IMPORT_PATH__'
// __INJECT:AUTH_IMPORT__

export async function POST(req: Request) {
// __INJECT:AUTH_CHECK__

  const { userId, fact } = await req.json()
  if (!userId?.trim() || !fact?.trim())
    return Response.json({ error: 'userId and fact are required' }, { status: 400 })

  const { embedding } = await embed({
    model: __EMBEDDING_CALL_EXPR__,
    value: fact,
  })

  await getMemoryStore().save({
    id: generateId(),
    userId,
    fact,
    embedding,
    createdAt: new Date(),
  })

  return Response.json({ ok: true })
}
