// Generated by ai-wingman — edit freely, you own this file.
//
// Orchestrator agent: breaks complex tasks into sub-tasks and delegates them to
// specialist agents via handoff tools. Specialists run synchronously within each
// tool call. The orchestrator streams its final synthesis back to the client.

import { convertToModelMessages, stepCountIs, streamText } from 'ai'
import { __PROVIDER_IMPORT__ } from '__PROVIDER_PACKAGE__'
import { handoffTools } from '__HANDOFF_TOOLS_IMPORT_PATH__'
// __INJECT:AUTH_IMPORT__

// Allow up to __MAX_DURATION__ seconds — the orchestrator may call multiple specialists in sequence
export const maxDuration = __MAX_DURATION__

export async function POST(req: Request) {
// __INJECT:AUTH_CHECK__

  const { messages } = await req.json()

  try {
    const result = streamText({
      model: __MODEL_FACTORY__,
      system:
        'You are an orchestrator. Break complex tasks into focused sub-tasks and' +
        ' delegate each to the appropriate specialist agent using the available tools.' +
        ' Synthesize the specialists\' results into a coherent final answer.',
      tools: handoffTools,
      stopWhen: stepCountIs(__MAX_STEPS__),
      messages: await convertToModelMessages(messages),
    })
    return result.toUIMessageStreamResponse()
  } catch {
    return Response.json({ error: 'Internal server error' }, { status: 500 })
  }
}
