'use client'

// Generated by ai-wingman — edit freely, you own this file.
// TODO: Add layout and styling around this component

import { useCallback, useRef, useState } from 'react'
import { useChat } from '@ai-sdk/react'
import { DefaultChatTransport, isFileUIPart, isTextUIPart } from 'ai'
import type { FileUIPart } from 'ai'
import {
  Conversation,
  ConversationContent,
  ConversationEmptyState,
  ConversationScrollButton,
} from '__PATH_ALIAS__components/ai-elements/conversation'
import {
  Message,
  MessageContent,
} from '__PATH_ALIAS__components/ai-elements/message'
import {
  PromptInput,
  PromptInputBody,
  PromptInputFooter,
  PromptInputSubmit,
  PromptInputTextarea,
  type PromptInputMessage,
} from '__PATH_ALIAS__components/ai-elements/prompt-input'

const API_PATH = '__API_PATH__'

// Converts a File to a FileUIPart (base64 data URL)
async function fileToUIPart(file: File): Promise<FileUIPart> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.onload = () => resolve({
      type: 'file',
      mediaType: file.type || 'image/jpeg',
      url: reader.result as string,
    })
    reader.onerror = reject
    reader.readAsDataURL(file)
  })
}

export default function MultimodalPage() {
  const [pendingFiles, setPendingFiles] = useState<FileUIPart[]>([])
  const fileInputRef = useRef<HTMLInputElement>(null)

  const { messages, sendMessage, status } = useChat({
    transport: new DefaultChatTransport({ api: API_PATH }),
  })

  const handleFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(e.target.files ?? [])
    const parts = await Promise.all(files.map(fileToUIPart))
    setPendingFiles((prev) => [...prev, ...parts])
    e.target.value = ''
  }

  const handleSubmit = useCallback((msg: PromptInputMessage) => {
    if (!msg.text?.trim() && pendingFiles.length === 0) return

    sendMessage({
      text: msg.text ?? '',
      ...(pendingFiles.length > 0 && { files: pendingFiles }),
    })

    setPendingFiles([])
  }, [sendMessage, pendingFiles])

  return (
    <div className="flex flex-col h-screen">
      <Conversation>
        <ConversationContent>
          {messages.length === 0 && (
            <ConversationEmptyState
              title="Multimodal chat"
              description="Send a message or attach an image to get started."
            />
          )}
          {messages.map((msg) => {
            const textParts = msg.parts.filter(isTextUIPart)
            const fileParts = msg.parts.filter(isFileUIPart)

            return (
              <Message key={msg.id} from={msg.role === 'user' ? 'user' : 'assistant'}>
                {textParts.map((p, i) => (
                  <MessageContent key={i}>
                    {p.text}
                  </MessageContent>
                ))}
                {fileParts.map((p, i) => (
                  // eslint-disable-next-line @next/next/no-img-element
                  <img
                    key={i}
                    src={p.url}
                    alt="Attached file"
                    className="max-w-xs rounded-md mt-1"
                  />
                ))}
              </Message>
            )
          })}
        </ConversationContent>
        <ConversationScrollButton />
      </Conversation>

      {pendingFiles.length > 0 && (
        <div className="flex gap-2 px-4 py-2 border-t flex-wrap">
          {pendingFiles.map((f, i) => (
            <div key={i} className="relative">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img src={f.url} alt="preview" className="h-16 w-16 object-cover rounded" />
              <button
                onClick={() => setPendingFiles((prev) => prev.filter((_, j) => j !== i))}
                className="absolute -top-1 -right-1 bg-destructive text-destructive-foreground rounded-full w-4 h-4 text-xs flex items-center justify-center"
              >
                ×
              </button>
            </div>
          ))}
        </div>
      )}

      <PromptInput onSubmit={handleSubmit} className="border-t">
        <PromptInputBody>
          <PromptInputTextarea placeholder="Type a message or attach an image..." />
        </PromptInputBody>
        <PromptInputFooter>
          <button
            type="button"
            onClick={() => fileInputRef.current?.click()}
            className="text-sm text-muted-foreground hover:text-foreground px-2"
            title="Attach image"
          >
            📎
          </button>
          <input
            ref={fileInputRef}
            type="file"
            accept="image/*"
            multiple
            className="hidden"
            onChange={handleFileChange}
          />
          <PromptInputSubmit status={status} disabled={status !== 'ready'} />
        </PromptInputFooter>
      </PromptInput>
    </div>
  )
}
