// Generated by ai-wingman — edit freely, you own this file.
//
// Specialist agents: each receives a HandoffPayload from the orchestrator and
// runs generateText synchronously, returning a plain string result back to the
// orchestrator. Swap generateText for streamText if you need per-specialist
// streaming.

import { generateText } from 'ai'
import { __PROVIDER_IMPORT__ } from '__PROVIDER_PACKAGE__'
import type { HandoffPayload } from '__TYPES_IMPORT_PATH__'

export async function researchSpecialist(payload: HandoffPayload): Promise<string> {
  const { text } = await generateText({
    model: __MODEL_FACTORY__,
    system: 'You are a research specialist. Find accurate information and summarize it concisely.',
    prompt: payload.context
      ? `${payload.task}\n\nContext: ${payload.context}`
      : payload.task,
  })
  return text
}

export async function writerSpecialist(payload: HandoffPayload): Promise<string> {
  const { text } = await generateText({
    model: __MODEL_FACTORY__,
    system: 'You are a writing specialist. Produce well-structured, polished prose.',
    prompt: payload.context
      ? `${payload.task}\n\nMaterial: ${payload.context}`
      : payload.task,
  })
  return text
}
