// Generated by ai-wingman — edit freely, you own this file.
//
// Handoff tools: typed wrappers that let the orchestrator delegate to specialists.
// Add more specialist tools here as your workflow grows.

import { tool } from 'ai'
import { z } from 'zod'
import { researchSpecialist, writerSpecialist } from '__SPECIALISTS_IMPORT_PATH__'
import type { HandoffPayload } from '__TYPES_IMPORT_PATH__'

export const handoffTools = {
  callResearcher: tool({
    description: 'Delegate a research sub-task to the research specialist agent.',
    parameters: z.object({
      task: z.string().describe('The research question or information-gathering task'),
      context: z.string().optional().describe('Additional conversation context'),
    }),
    execute: async (args): Promise<string> => {
      const payload: HandoffPayload = args
      return researchSpecialist(payload)
    },
  }),
  callWriter: tool({
    description: 'Delegate a writing or editing sub-task to the writer specialist agent.',
    parameters: z.object({
      task: z.string().describe('The writing or editing task to perform'),
      context: z.string().optional().describe('Research notes or material to incorporate'),
    }),
    execute: async (args): Promise<string> => {
      const payload: HandoffPayload = args
      return writerSpecialist(payload)
    },
  }),
}
