// Generated by ai-wingman — edit freely, you own this file.
//
// Accepts { messages } where messages may contain image parts alongside text.
// Image parts are passed as data URIs from the client.
// See: https://sdk.vercel.ai/docs/foundations/prompts#image-parts

import { convertToModelMessages, streamText } from 'ai'
import { __PROVIDER_IMPORT__ } from '__PROVIDER_PACKAGE__'
// __INJECT:AUTH_IMPORT__

export const maxDuration = __MAX_DURATION__

export async function POST(req: Request) {
// __INJECT:AUTH_CHECK__

  const { messages } = await req.json()

  const result = streamText({
    model: __MODEL_FACTORY__,
    system: 'You are a helpful assistant. When images are provided, analyze them carefully.',
    messages: await convertToModelMessages(messages),
  })

  return result.toUIMessageStreamResponse()
}
