// Generated by ai-wingman — edit freely, you own this file.
//
// Shared types for the multi-agent handoff protocol.

/** Payload passed from the orchestrator to each specialist agent. */
export interface HandoffPayload {
  /** The sub-task for the specialist to complete. */
  task: string
  /** Optional extra context from the orchestrator conversation. */
  context?: string
}
