// Generated by ai-wingman — edit freely, you own this file.

import { cosineSimilarity } from 'ai'
import type { RagChunk, RagStore } from './store.js'

export class MemoryRagStore implements RagStore {
  private chunks: Required<RagChunk>[] = []

  async upsert(chunk: Required<RagChunk>): Promise<void> {
    const idx = this.chunks.findIndex((c) => c.id === chunk.id)
    if (idx >= 0) {
      this.chunks[idx] = chunk
    } else {
      this.chunks.push(chunk)
    }
  }

  async query({ embedding, topK }: { embedding: number[]; topK: number }): Promise<RagChunk[]> {
    return this.chunks
      .map((c) => ({ chunk: c, score: cosineSimilarity(embedding, c.embedding) }))
      .sort((a, b) => b.score - a.score)
      .slice(0, topK)
      .map(({ chunk }) => ({ id: chunk.id, text: chunk.text }))
  }
}
