// Generated by ai-wingman — edit freely, you own this file.

import { MemoryRagStore } from '__MEMORY_IMPORT_PATH__'
import { SqliteRagStore } from '__SQLITE_IMPORT_PATH__'

export interface RagChunk {
  id: string
  text: string
  embedding?: number[]
}

export interface RagStore {
  upsert(chunk: Required<RagChunk>): Promise<void>
  query(params: { embedding: number[]; topK: number }): Promise<RagChunk[]>
}

let _store: RagStore | undefined

export function getRagStore(): RagStore {
  if (_store) return _store
  const backend = process.env['RAG_STORAGE'] ?? 'memory'
  if (backend === 'sqlite') {
    _store = new SqliteRagStore()
  } else {
    _store = new MemoryRagStore()
  }
  return _store
}
