// Generated by ai-wingman — edit freely, you own this file.

import { MemoryRagStore } from '__MEMORY_IMPORT_PATH__'

export interface RagChunk {
  id: string
  text: string
  embedding?: number[]
}

export interface RagStore {
  upsert(chunk: Required<RagChunk>): Promise<void>
  query(params: { embedding: number[]; topK: number }): Promise<RagChunk[]>
}

let _store: RagStore | undefined

export function getRagStore(): RagStore {
  if (_store) return _store
  _store = new MemoryRagStore()
  return _store
}
