// Generated by ai-wingman — edit freely, you own this file.

'use client'

import { useState } from 'react'

export function useRagQuery() {
  const [result, setResult] = useState<string | null>(null)
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState<Error | null>(null)

  async function query(input: string, topK = 5) {
    setIsLoading(true)
    setError(null)
    try {
      const res = await fetch('__API_PATH__', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ query: input, topK }),
      })
      const data = await res.json() as { text: string }
      setResult(data.text)
    } catch (err) {
      setError(err instanceof Error ? err : new Error(String(err)))
    } finally {
      setIsLoading(false)
    }
  }

  return { result, isLoading, error, query }
}
