// Generated by ai-wingman — edit freely, you own this file.

'use client'

import { useRef, useState } from 'react'

export function useRagQuery() {
  const [result, setResult] = useState<string>('')
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState<Error | null>(null)
  const readerRef = useRef<ReadableStreamDefaultReader<string> | null>(null)

  async function query(input: string, topK = 5) {
    setIsLoading(true)
    setResult('')
    setError(null)

    try {
      const res = await fetch('__API_PATH__', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ query: input, topK }),
      })

      if (!res.body) throw new Error('No response body')

      const reader = res.body.pipeThrough(new TextDecoderStream()).getReader()
      readerRef.current = reader

      while (true) {
        const { done, value } = await reader.read()
        if (done) break
        setResult((prev) => prev + value)
      }
    } catch (err) {
      setError(err instanceof Error ? err : new Error(String(err)))
    } finally {
      setIsLoading(false)
      readerRef.current = null
    }
  }

  function stop() {
    readerRef.current?.cancel()
  }

  return { result, isLoading, error, query, stop }
}
