// Generated by ai-wingman — edit freely, you own this file.

import { embed, streamText } from 'ai'
import { __PROVIDER_IMPORT__ } from '__PROVIDER_PACKAGE__'
import { getRagStore } from '__STORE_IMPORT_PATH__'
// __INJECT:AUTH_IMPORT__

export async function POST(req: Request) {
// __INJECT:AUTH_CHECK__

  const { query, topK = 5 } = await req.json()

  const { embedding } = await embed({
    model: __EMBEDDING_CALL_EXPR__,
    value: query,
  })

  const store = getRagStore()
  const chunks = await store.query({ embedding, topK })
  const context = chunks.map((c) => c.text).join('\n\n')

  const result = await streamText({
    model: __MODEL_FACTORY__,
    system: [
      'Answer using only the context below. If the answer is not in the context, say so.',
      '',
      'Context:',
      context,
    ].join('\n'),
    prompt: query,
  })

  return result.toTextStreamResponse()
}
