// Generated by ai-wingman — edit freely, you own this file.
//
// SQLite + sqlite-vec vector store. Zero infrastructure required — just a local .db file.
// Install: pnpm add better-sqlite3 sqlite-vec
// Types:   pnpm add -D @types/better-sqlite3
//
// The sqlite-vec extension stores vectors as blobs and retrieves them with
// vec_distance_cosine(). See: https://alexgarcia.xyz/sqlite-vec

import Database from 'better-sqlite3'
import * as sqliteVec from 'sqlite-vec'
import type { RagChunk, RagStore } from './store.js'

const DB_PATH = process.env['SQLITE_RAG_PATH'] ?? '.rag.db'

function getDb(): Database.Database {
  const db = new Database(DB_PATH)
  sqliteVec.load(db)
  db.exec(`
    CREATE TABLE IF NOT EXISTS rag_chunks (
      id    TEXT PRIMARY KEY,
      text  TEXT NOT NULL,
      embedding BLOB NOT NULL
    );
    CREATE VIRTUAL TABLE IF NOT EXISTS rag_vec USING vec0(
      id    TEXT PRIMARY KEY,
      embedding FLOAT[1536]
    );
  `)
  return db
}

export class SqliteRagStore implements RagStore {
  private db = getDb()

  async upsert(chunk: Required<RagChunk>): Promise<void> {
    const embeddingBlob = Buffer.from(new Float32Array(chunk.embedding).buffer)
    this.db.prepare(`
      INSERT INTO rag_chunks (id, text, embedding) VALUES (?, ?, ?)
      ON CONFLICT (id) DO UPDATE SET text = excluded.text, embedding = excluded.embedding
    `).run(chunk.id, chunk.text, embeddingBlob)

    this.db.prepare(`
      INSERT INTO rag_vec (id, embedding) VALUES (?, ?)
      ON CONFLICT (id) DO UPDATE SET embedding = excluded.embedding
    `).run(chunk.id, embeddingBlob)
  }

  async query({ embedding, topK }: { embedding: number[]; topK: number }): Promise<RagChunk[]> {
    const queryBlob = Buffer.from(new Float32Array(embedding).buffer)
    const rows = this.db.prepare<[Buffer, number], { id: string; text: string }>(`
      SELECT c.id, c.text
      FROM rag_vec v
      JOIN rag_chunks c ON c.id = v.id
      WHERE v.embedding MATCH ?
        AND k = ?
      ORDER BY distance
    `).all(queryBlob, topK)
    return rows.map((r) => ({ id: r.id, text: r.text }))
  }
}
