// Generated by ai-wingman — edit freely, you own this file.
//
// Splits text into overlapping fixed-size chunks, breaking at sentence
// boundaries when possible.
//
// Usage:
//   import { chunkText } from './chunker.js'
//   const chunks = chunkText('Long document text...')

export interface ChunkOptions {
  /** Target chunk size in characters (default: __CHUNK_SIZE__) */
  chunkSize?: number
  /** Overlap between consecutive chunks in characters (default: 10% of chunkSize) */
  overlap?: number
  /** Break at sentence boundaries when a terminator is found near the chunk end */
  sentenceBoundary?: boolean
}

const SENTENCE_TERMINATORS = /[.!?]\s/g

/**
 * Splits `text` into an array of overlapping chunks.
 *
 * Strategy:
 * 1. Find the natural chunk end at chunkSize characters.
 * 2. If sentenceBoundary is true, scan backwards for a sentence terminator
 *    within the last 20% of the chunk. Split there if found.
 * 3. Start the next chunk `overlap` characters before the end of the previous one.
 */
export function chunkText(text: string, options: ChunkOptions = {}): string[] {
  const chunkSize = options.chunkSize ?? __CHUNK_SIZE__
  const overlap = options.overlap ?? Math.floor(chunkSize * 0.1)
  const sentenceBoundary = options.sentenceBoundary ?? true

  if (text.length <= chunkSize) return [text]

  const chunks: string[] = []
  let start = 0

  while (start < text.length) {
    const end = Math.min(start + chunkSize, text.length)
    let splitAt = end

    if (sentenceBoundary && end < text.length) {
      // Scan backwards within the last 20% of the chunk for a sentence terminator
      const scanFrom = Math.max(start, end - Math.floor(chunkSize * 0.2))
      const window = text.slice(scanFrom, end)
      let lastTerminator = -1
      SENTENCE_TERMINATORS.lastIndex = 0
      let match: RegExpExecArray | null
      while ((match = SENTENCE_TERMINATORS.exec(window)) !== null) {
        lastTerminator = match.index
      }
      if (lastTerminator >= 0) {
        splitAt = scanFrom + lastTerminator + 1
      }
    }

    chunks.push(text.slice(start, splitAt).trim())
    start = splitAt - overlap
  }

  return chunks.filter((c) => c.length > 0)
}
