-- Generated by ai-wingman — edit freely, you own this file.
-- Run this once against your database before starting the app.

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS rag_chunks (
  id        TEXT PRIMARY KEY,
  text      TEXT NOT NULL,
  -- TODO: dimension must match your embedding model (1536 = text-embedding-3-small)
  embedding VECTOR(1536)
);

CREATE INDEX IF NOT EXISTS rag_chunks_embedding_idx
  ON rag_chunks USING ivfflat (embedding vector_cosine_ops);
