// Generated by ai-wingman — edit freely, you own this file.

import postgres from 'postgres'
import type { RagChunk, RagStore } from './store.js'

const sql = postgres(process.env['POSTGRES_URL']!)

export class PgvectorRagStore implements RagStore {
  async upsert(chunk: Required<RagChunk>): Promise<void> {
    const vectorLiteral = `[${chunk.embedding.join(',')}]`
    await sql`
      INSERT INTO rag_chunks (id, text, embedding)
      VALUES (${chunk.id}, ${chunk.text}, ${vectorLiteral}::vector)
      ON CONFLICT (id) DO UPDATE
        SET text = EXCLUDED.text,
            embedding = EXCLUDED.embedding
    `
  }

  async query({ embedding, topK }: { embedding: number[]; topK: number }): Promise<RagChunk[]> {
    const vectorLiteral = `[${embedding.join(',')}]`
    const rows = await sql<{ id: string; text: string }[]>`
      SELECT id, text
      FROM rag_chunks
      ORDER BY embedding <=> ${vectorLiteral}::vector
      LIMIT ${topK}
    `
    return rows.map((r) => ({ id: r.id, text: r.text }))
  }
}
