// Generated by ai-wingman — edit freely, you own this file.

import { embed } from 'ai'
import { __PROVIDER_IMPORT__ } from '__PROVIDER_PACKAGE__'
import { getRagStore } from '__STORE_IMPORT_PATH__'
// __INJECT:AUTH_IMPORT__

export async function POST(req: Request) {
// __INJECT:AUTH_CHECK__

  const { text } = await req.json()

  const store = getRagStore()

  const { embedding } = await embed({
    model: __EMBEDDING_CALL_EXPR__,
    value: text,
  })

  await store.upsert({
    id: crypto.randomUUID(),
    text,
    embedding,
  })

  return Response.json({ ok: true })
}
