// Generated by ai-wingman — edit freely, you own this file.

'use client'

import { experimental_useObject as useObject } from '@ai-sdk/react'
import { __SCHEMA_VAR_NAME__ } from '__SCHEMA_IMPORT_PATH__'

export function __HOOK_NAME__() {
  const { object, isLoading, error, submit: submitObject } = useObject({
    api: '__API_PATH__',
    schema: __SCHEMA_VAR_NAME__,
  })

  function submit(prompt: string) {
    submitObject({ prompt })
  }

  return { object, isLoading, error, submit } satisfies {
    object: import('ai').DeepPartial<import('zod').infer<typeof __SCHEMA_VAR_NAME__>> | undefined
    isLoading: boolean
    error: Error | undefined
    submit: (prompt: string) => void
  }
}
