// Generated by ai-wingman — edit freely, you own this file.

import { streamObject } from 'ai'
import { __PROVIDER_IMPORT__ } from '__PROVIDER_PACKAGE__'
import { __SCHEMA_VAR_NAME__ } from '__SCHEMA_IMPORT_PATH__'
// __INJECT:AUTH_IMPORT__

export async function POST(req: Request) {
// __INJECT:AUTH_CHECK__

  const { prompt } = await req.json()

  const result = streamObject({
    model: __MODEL_FACTORY__,
    schema: __SCHEMA_VAR_NAME__,
    prompt,
  })

  return result.toTextStreamResponse()
}
