// Generated by ai-wingman — edit freely, you own this file.

import { z } from 'zod'

// TODO: define your schema
export const __SCHEMA_VAR_NAME__ = z.object({
  // example:
  // field: z.string(),
  // items: z.array(z.string()),
})

export type __TYPE_NAME__ = z.infer<typeof __SCHEMA_VAR_NAME__>
