// Generated by ai-wingman — edit freely, you own this file.

import { useState } from 'react'
import type { __TYPE_NAME__ } from '__SCHEMA_IMPORT_PATH__'

export function __HOOK_NAME__() {
  const [result, setResult] = useState<__TYPE_NAME__ | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  async function generate(input: string) {
    setLoading(true)
    setError(null)
    try {
      const res = await fetch('__API_URL__', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ input }),
      })
      if (!res.ok) throw new Error(`Request failed: ${res.status}`)
      setResult(await res.json())
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Unknown error')
    } finally {
      setLoading(false)
    }
  }

  return { result, loading, error, generate }
}
