// Generated by ai-wingman — edit freely, you own this file.

import { convertToModelMessages, stepCountIs, streamText } from 'ai'
import { __PROVIDER_IMPORT__ } from '__PROVIDER_PACKAGE__'
import { __TOOLS_VAR_NAME__ } from '__TOOLS_IMPORT_PATH__'
// __INJECT:AUTH_IMPORT__

// Allow streaming responses up to 30 seconds
export const maxDuration = 30

export async function POST(req: Request) {
// __INJECT:AUTH_CHECK__

  const { messages } = await req.json()

  try {
    const result = streamText({
      model: __MODEL_FACTORY__,
      tools: __TOOLS_VAR_NAME__,
      stopWhen: stepCountIs(5),
      messages: await convertToModelMessages(messages),
      // onStepFinish: async ({ stepType, toolCalls, toolResults }) => {
      //   console.log({ stepType, toolCalls, toolResults })
      // },
    })
    return result.toUIMessageStreamResponse()
  } catch {
    return Response.json({ error: 'Internal server error' }, { status: 500 })
  }
}
