// Generated by ai-wingman — edit freely, you own this file.

export interface Product {
  id: string
  name: string
  price: number
  description: string
  emoji: string
}

export const PRODUCTS: Product[] = [
  { id: 'p1', name: 'Wireless Headphones', price: 149, description: 'Over-ear, 30hr battery, noise cancelling', emoji: '🎧' },
  { id: 'p2', name: 'Mechanical Keyboard',  price:  89, description: 'Compact TKL layout, tactile switches',    emoji: '⌨️' },
  { id: 'p3', name: 'USB-C Hub',            price:  49, description: '7-in-1: HDMI, USB-A ×3, SD, PD',         emoji: '🔌' },
  { id: 'p4', name: 'Desk Lamp',            price:  39, description: 'LED, adjustable colour temp, USB charging', emoji: '💡' },
  { id: 'p5', name: 'Webcam 4K',            price: 119, description: 'Auto-focus, built-in ring light',         emoji: '📷' },
]

// NOTE: Session ID is hardcoded — this is a demo with shared state.
// In production, derive the session key from the user's auth session or a cookie.
type State = { wishlist: Set<string>; cart: Map<string, number> }
const store: State = { wishlist: new Set(), cart: new Map() }

export function addToWishlist(productId: string): { already: boolean } {
  const already = store.wishlist.has(productId)
  store.wishlist.add(productId)
  return { already }
}

export function addToCart(productId: string): { qty: number } {
  const qty = (store.cart.get(productId) ?? 0) + 1
  store.cart.set(productId, qty)
  return { qty }
}

export function formatWishlist(): string {
  if (store.wishlist.size === 0) return 'Wishlist: empty'
  const items = [...store.wishlist].map(id => {
    const p = PRODUCTS.find(p => p.id === id)
    return p ? `${p.emoji} ${p.name}` : id
  })
  return `Wishlist: ${items.join(', ')}`
}

export function formatCart(): string {
  if (store.cart.size === 0) return 'Cart: empty'
  const items = [...store.cart.entries()].map(([id, qty]) => {
    const p = PRODUCTS.find(p => p.id === id)
    return p ? `${p.emoji} ${p.name} ×${qty}` : `${id} ×${qty}`
  })
  return `Cart: ${items.join(', ')}`
}
