// Generated by ai-wingman — edit freely, you own this file.

import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import { WebStandardStreamableHTTPServerTransport } from '@modelcontextprotocol/sdk/server/webStandardStreamableHttp.js'
import { randomUUID } from 'crypto'
import { readFileSync } from 'fs'
import { join } from 'path'
import { z } from 'zod'
import {
  PRODUCTS,
  addToCart,
  addToWishlist,
  formatCart,
  formatWishlist,
} from '@/lib/mcp-product-wishlist-state'

// fs and crypto require Node.js runtime
export const runtime = 'nodejs'

const RESOURCE_URI = 'ui://product-wishlist'
// Standard MIME type for MCP App HTML resources — hosts use this to identify interactive UIs
const RESOURCE_MIME_TYPE = 'text/html;profile=mcp-app'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, mcp-session-id, mcp-protocol-version',
  'Access-Control-Expose-Headers': 'mcp-session-id',
}

function withCors(response: Response): Response {
  const newResponse = new Response(response.body, response)
  Object.entries(corsHeaders).forEach(([key, value]) => {
    newResponse.headers.set(key, value)
  })
  return newResponse
}

// Session store — persists across requests within the Node.js process lifetime
const sessions = new Map<string, WebStandardStreamableHTTPServerTransport>()

function createServer() {
  const server = new McpServer({ name: 'ProductWishlist', version: '1.0.0' })

  // Resource: the interactive HTML UI bundle.
  // mimeType must be 'text/html;profile=mcp-app' so hosts identify this as an MCP App.
  server.resource(RESOURCE_URI, RESOURCE_URI, { mimeType: RESOURCE_MIME_TYPE }, async () => ({
    contents: [{
      uri: RESOURCE_URI,
      mimeType: RESOURCE_MIME_TYPE,
      // Use a function replacement to prevent $ patterns in the bundle being interpreted as replacement tokens.
      text: (() => {
        const bundle = readFileSync(join(process.cwd(), 'public/mcp-apps/product-wishlist/app-with-deps.js'), 'utf-8')
        return readFileSync(join(process.cwd(), 'public/mcp-apps/product-wishlist/index.html'), 'utf-8')
          .replace('__BUNDLE_CONTENT__', () => bundle)
      })(),
    }],
  }))

  // Tool: browse products — _meta.ui.resourceUri in the definition tells hosts to render the UI panel.
  server.registerTool(
    'product_wishlist_browse',
    {
      description: 'Show the interactive product catalog with wishlist and cart buttons.',
      _meta: {
        ui: { resourceUri: RESOURCE_URI },
        'ui/resourceUri': RESOURCE_URI, // legacy compat for older hosts
      },
    },
    async () => ({
      content: [{
        type: 'text' as const,
        text: `Here are the products. Use the buttons in the panel to add items to your wishlist or cart.\n\n${PRODUCTS.map(p => `${p.emoji} **${p.name}** — $${p.price}\n   ${p.description}`).join('\n\n')}`,
      }],
    })
  )

  // Tool: add to wishlist — called by the UI via app.callServerTool
  server.registerTool(
    'product_wishlist_add_to_wishlist',
    {
      description: 'Add a product to the wishlist.',
      inputSchema: { productId: z.string().describe('Product ID (p1–p5)') },
      _meta: {
        ui: { resourceUri: RESOURCE_URI, visibility: ['app'] },
        'ui/resourceUri': RESOURCE_URI,
      },
    },
    async ({ productId }) => {
      const product = PRODUCTS.find(p => p.id === productId)
      if (!product) return { content: [{ type: 'text' as const, text: `Unknown product: ${productId}` }] }
      const { already } = addToWishlist(productId)
      return {
        content: [{
          type: 'text' as const,
          text: already
            ? `${product.emoji} ${product.name} is already in your wishlist.`
            : `Added ${product.emoji} ${product.name} to wishlist.\n\n${formatWishlist()}`,
        }],
      }
    }
  )

  // Tool: add to cart — called by the UI via app.callServerTool
  server.registerTool(
    'product_wishlist_add_to_cart',
    {
      description: 'Add a product to the shopping cart.',
      inputSchema: { productId: z.string().describe('Product ID (p1–p5)') },
      _meta: {
        ui: { resourceUri: RESOURCE_URI, visibility: ['app'] },
        'ui/resourceUri': RESOURCE_URI,
      },
    },
    async ({ productId }) => {
      const product = PRODUCTS.find(p => p.id === productId)
      if (!product) return { content: [{ type: 'text' as const, text: `Unknown product: ${productId}` }] }
      const { qty } = addToCart(productId)
      return {
        content: [{
          type: 'text' as const,
          text: `Added ${product.emoji} ${product.name} to cart (×${qty}).\n\n${formatCart()}`,
        }],
      }
    }
  )

  // Tool: view summary — model-initiated, shows current cart and wishlist
  server.tool(
    'product_wishlist_summary',
    'Show the current cart and wishlist contents.',
    {},
    async () => ({
      content: [{
        type: 'text' as const,
        text: `${formatCart()}\n\n${formatWishlist()}`,
      }],
    })
  )

  return server
}

// Helper — create a new transport+server pair, store session, return the response
async function handleNewSession(req: Request): Promise<Response> {
  const transport = new WebStandardStreamableHTTPServerTransport({
    sessionIdGenerator: () => randomUUID(),
  })
  const server = createServer()
  await server.connect(transport)
  const response = await transport.handleRequest(req)
  if (transport.sessionId) {
    sessions.set(transport.sessionId, transport)
    transport.onclose = () => sessions.delete(transport.sessionId!)
  }
  return response
}

// OPTIONS — handle CORS preflight
export async function OPTIONS() {
  return new Response(null, { status: 204, headers: corsHeaders })
}

// GET — SSE stream for existing session (server-to-client notifications)
export async function GET(req: Request) {
  const sessionId = req.headers.get('mcp-session-id')
  if (sessionId) {
    const transport = sessions.get(sessionId)
    if (!transport) return withCors(new Response('Session not found', { status: 404 }))
    return withCors(await transport.handleRequest(req))
  }
  return withCors(await handleNewSession(req))
}

// POST — initialize (no session ID) or route to existing session
export async function POST(req: Request) {
  const sessionId = req.headers.get('mcp-session-id')
  if (!sessionId) return withCors(await handleNewSession(req))
  const transport = sessions.get(sessionId)
  if (!transport) return withCors(new Response('Session not found', { status: 404 }))
  return withCors(await transport.handleRequest(req))
}

// DELETE — terminate session and release resources
export async function DELETE(req: Request) {
  const sessionId = req.headers.get('mcp-session-id')
  if (sessionId) {
    await sessions.get(sessionId)?.close()
    sessions.delete(sessionId)
  }
  return withCors(new Response(null, { status: 204 }))
}
