// AUTO-GENERATED by scripts/generate-pattern-registry.ts — do not edit manually.
// To regenerate: npm run generate:registry

import { agentPattern } from '../patterns/agent/index.js'
import { audioPattern } from '../patterns/audio/index.js'
import { backgroundAgentPattern } from '../patterns/background-agent/index.js'
import { chatPattern } from '../patterns/chat/index.js'
import { contentModerationPattern } from '../patterns/content-moderation/index.js'
import { documentProcessingPattern } from '../patterns/document-processing/index.js'
import { evalPattern } from '../patterns/eval/index.js'
import { generativeUiPattern } from '../patterns/generative-ui/index.js'
import { hybridSearchPattern } from '../patterns/hybrid-search/index.js'
import { imageGenPattern } from '../patterns/image-gen/index.js'
import { interruptPattern } from '../patterns/interrupt/index.js'
import { memoryPattern } from '../patterns/memory/index.js'
import { multiAgentPattern } from '../patterns/multi-agent/index.js'
import { multimodalPattern } from '../patterns/multimodal/index.js'
import { ragPattern } from '../patterns/rag/index.js'
import { streamObjectPattern } from '../patterns/stream-object/index.js'
import { structuredOutputPattern } from '../patterns/structured-output/index.js'
import { toolsPattern } from '../patterns/tools/index.js'
import type { Pattern } from '../types.js'

const patternRegistry: Pattern[] = [
  agentPattern,
  audioPattern,
  backgroundAgentPattern,
  chatPattern,
  contentModerationPattern,
  documentProcessingPattern,
  evalPattern,
  generativeUiPattern,
  hybridSearchPattern,
  imageGenPattern,
  interruptPattern,
  memoryPattern,
  multiAgentPattern,
  multimodalPattern,
  ragPattern,
  streamObjectPattern,
  structuredOutputPattern,
  toolsPattern,
]

export function resolvePatterns(ids: string[]): Pattern[] {
  return ids.map((id) => {
    const p = patternRegistry.find((p) => p.id === id)
    if (!p) {
      const valid = patternRegistry.map((p) => p.id).join(', ')
      throw new Error(`Unknown pattern "${id}". Valid patterns: ${valid}`)
    }
    return p
  })
}

export function resolveAllPatterns(): Pattern[] {
  return patternRegistry
}
