/**
 * Scans src/patterns/* and generates src/registry/patterns.ts.
 * Run via `npm run generate:registry` or automatically on `npm run build`.
 */

import { readdirSync, readFileSync, writeFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const patternsDir = resolve(__dirname, '../src/patterns')
const outputFile = resolve(__dirname, '../src/registry/patterns.ts')

const dirs = readdirSync(patternsDir, { withFileTypes: true })
  .filter(d => d.isDirectory())
  .sort((a, b) => a.name.localeCompare(b.name))

function kebabToCamel(s: string): string {
  return s.replace(/-([a-z])/g, (_, c) => c.toUpperCase())
}

// Verify each pattern directory has an index.ts with the expected export
for (const d of dirs) {
  const indexPath = resolve(patternsDir, d.name, 'index.ts')
  const exportName = `${kebabToCamel(d.name)}Pattern`
  let content: string
  try {
    content = readFileSync(indexPath, 'utf-8')
  } catch {
    console.error(`Missing index.ts in src/patterns/${d.name}/`)
    process.exit(1)
  }
  if (!content.includes(exportName)) {
    console.error(
      `Expected export "${exportName}" in src/patterns/${d.name}/index.ts`
    )
    process.exit(1)
  }
}

const imports = dirs.map(d => {
  const exportName = `${kebabToCamel(d.name)}Pattern`
  return `import { ${exportName} } from '../patterns/${d.name}/index.js'`
})

const entries = dirs.map(d => `  ${kebabToCamel(d.name)}Pattern,`)

const content = `// AUTO-GENERATED by scripts/generate-pattern-registry.ts — do not edit manually.
// To regenerate: npm run generate:registry

${imports.join('\n')}
import type { Pattern } from '../types.js'

const patternRegistry: Pattern[] = [
${entries.join('\n')}
]

export function resolvePatterns(ids: string[]): Pattern[] {
  return ids.map((id) => {
    const p = patternRegistry.find((p) => p.id === id)
    if (!p) {
      const valid = patternRegistry.map((p) => p.id).join(', ')
      throw new Error(\`Unknown pattern "\${id}". Valid patterns: \${valid}\`)
    }
    return p
  })
}

export function resolveAllPatterns(): Pattern[] {
  return patternRegistry
}
`

const existing = readFileSync(outputFile, 'utf-8').trimEnd()
if (existing === content.trimEnd()) {
  console.log(`Registry up-to-date (${dirs.length} patterns)`)
} else {
  writeFileSync(outputFile, content)
  console.log(`Generated registry with ${dirs.length} patterns`)
}
